// Generated by CoffeeScript 1.9.2
module.exports.fragments_config_postgresPoolSize = function(envStringDatabaseUrl) {
  return envStringDatabaseUrl;
};

module.exports.fragments_config_postgresPoolSize = function(envIntPostgresPoolSize) {
  return envIntPostgresPoolSize;
};
