// Generated by CoffeeScript 1.9.3
module.exports.fragments_config_databaseUrl = function(envStringDatabaseUrl) {
  return envStringDatabaseUrl;
};

module.exports.fragments_config_postgresPoolSize = function(envIntPostgresPoolSize) {
  return envIntPostgresPoolSize;
};

module.exports.fragments_config_migrationPath = function(envStringMigrationPath) {
  return envStringMigrationPath;
};

module.exports.fragments_config_postgresDatabase = function(envStringPostgresDatabase) {
  return envStringPostgresDatabase;
};
